### PR TITLE
Switcher

### PR DESCRIPTION
**Pull request by xinetzone**
Add `switcher.rst` pages for switching translations.

### CODE REVIEW

**Comment by xinetzone** [comment]
`download.rst` is doing well!

**Comment by kayhayen** [comment]
I was thinking more of something like where the social buttons live @xinetzone but not in the menu, I think space there is too valuable, and no word ever, is going to catch it, such that people will have this.

I am searching for copyright clean way to download matching flags. When I have this, there will be some flag near the social buttons, with CSS styling to enlarge on mouse over, and some click handling of the flags to go to other URLs, or maybe simply one page, which lists all available translations. Unfortunately, Sphinx has nothing that helps us here.

**Comment by xinetzone** [comment]
see [sphinx-togglebutton](https://sphinx-togglebutton.readthedocs.io/en/latest/).

**Comment by kayhayen** [comment]
They themselves say: 

> For a bootstrap-based “dropdown” directive that uses pure CSS, check out [Sphinx Design](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html)

Pure CSS is always the best. I will add one to my welcome page now, so we can see it in action, and what HTML is behind it.

**Pull request merged**
