### PR TITLE
Translation merge

### PR DESCRIPTION
**Pull request by kayhayen**
This pull request aims at merging the infrastructure for translation created by @xinetzone and to provide a basis for collaboration.

### CODE REVIEW

**Comment by kayhayen** [comment]
@xinetzone @Fire-Cube Lets continue here, because code diff will be meaningful.

**Comment by Fire-Cube** [comment]
What all translations do we want to keep?

**Comment by kayhayen** [comment]
I am for translating nearly everything under pages, that is recent information:

donations.rst  
overview.rst (this one is a duplicate of content currently in index.rst and not linked, ignore for now)
pyside2.rst 
support.rst (this one is not mentioning the Discord server yet, I will add that soon though)
gsoc2019.rst (this one is historical information, I don't think translation makes sense, not sure what to do with it)
impressum.rst (this one is required by law in my country, translators might want to add their information here)
Presentations.rst (this one probably should get more love content wise)
Streaming.rst (since this about an English offer, not sure it makes sense, I will also update it in near future somewhat)

I will come up with a better directory structure too, but git renames are hopefully not an issue there.

In the doc folder, this is that:

api-doc.rst   (translation makes no sense)
commercial.rst (translation very welcome)
commercial (all in there very welcome)
factory.rst  (very useful to translate)
welcome.rst (this is just a playground for me, do not translate, unless we want to play around with translation mechanics)
Changelog.rst  (do not translate, this is a bizarre amount of work)
download.rst  (very welcome, but beware that download.rst.j2  is the real source). Tables are generated into the document, this is probably a harder case.
developer-manual.rst  (makes no sense to translate) Logo         
roadmap.rst (much like changelog, not as much work, but also not as important)
user-manual.rst (this one is most important in my mind, optimization section needs  a serious update from my side, maybe ignore that)

I will update the `README.rst` with a section that details this tomorrow.

What I would suggest actually is for you to first review the documents. I think the User Manual still contains content that doesn't really belong there. I moved some things to Credits.rst already, but there is probably more. We should first cleanup the document content maybe. For joining Nuitka, we probably should point to Discord server and Github issues, and PRs, rather than mentioning branches. But generally User Manual ought to be good.

**Comment by xinetzone** [comment]
I'm trying to rewrite `_docs.py`. 

We can refer to [configuration](https://daobook.github.io/invoke/docs/concepts/configuration.html) for relevant content.

**Comment by kayhayen** [comment]
Yes, Yaml configuration would be nice indeed. I think you ought to rebase. In the `git diff --stat` to `main` I see a lot of files, and generally `doc/doc/_static` and `doc/doc/_templates` that should not exist, or should they? I think you won't have to mess with these files anymore. On current main there are no symlinks anymore.

And a note regarding the `virtualenv` task. You only need to pipenv install with `--dev` for human tasks, or at least that is the plan, so e.g. `black` formatting of Python is nothing needed by CI, but e.g. a commit hook should apply. I guess invoke can layer this in a way such that it does it only when necessary?

For me, most strange right now is the PNG/SVG file differences, or are these things you want to translate as well?

**Comment by xinetzone** [comment]
I did not modify the 'doc/' folder for the translation documents. Those changes should be made automatically by 'update.py'.

**Comment by kayhayen** [comment]
Let me give it a try, I will rebase translation and check out, what I mean with changed or added files, trying to remove  that.

**Comment by kayhayen** [comment]
After rebasing I got e.g. that:

```
git log doc/doc/Nuitka-Logo-Symbol.png
commit 0105cc8f700230a248afcb5fdcdd13c6fb31ed9c
Author: xinetzone <xinzone@outlook.com>
Date:   Thu Feb 10 11:50:26 2022 +0800

            modified:   _docs.py
```

And this:

./doc/doc/doc/Nuitka-Logo-Symbol.png
./doc/doc/Nuitka-Logo-Symbol.png
./doc/Nuitka-Logo-Symbol.png

On main branch, only the last one exists, so I believe something strange might have happened there. I blame the symlinks and I will try and cleanup the branch from these changes now.

**Comment by kayhayen** [comment]
Nah, I think I may not know what I am doing there. 

@xinetzone would you be available for a telco, then email me privately, where we can share screen, and you explain to me what `sphinx-intl` requires from us there. 

I am not sure that some of that needs to be in the repo. Copies of the images are definitely ugly. So far I am getting that it created under "sites" in a folder. But is that maybe only needed temporary, and under `locales` is what we need? And from what I see, below `intl` there is a new configuration of sphinx.

I have no clue of these things, unfortunately, but wouldn't it be better if one config addressed all the site?

**Comment by xinetzone** [comment]
I'm sorry, I don't know how to operate a telecommute.

`sphinx-intl` is only used to generate the initial dictionary for the translated document, so as long as the document is not updated, translators are only concerned with translating the content of `locals/`.

**Comment by xinetzone** [comment]
`doc/conf.py` ：
```python
# Sphinx intl configuration
locale_dirs = ['locale/']
gettext_compact = False
```

replaced：

```python
# Sphinx intl configuration
locale_dirs = ['locales/']
gettext_compact = False
```

Can maintain unity.

**Comment by xinetzone** [comment]
Update the POT:

```python
invoke doc.update
```

Update the `locals/`：

```python
invoke intl.updte -l zh_CN
```

More languages:

```python
invoke intl.updte -l zh_CN,de
```

**Comment by xinetzone** [comment]
```
doc/doc/download.rst:523: WARNING: image file not readable: images/windows.jpg
doc/doc/download.rst:523: WARNING: image file not readable: images/windows.jpg
doc/doc/download.rst:509: WARNING: image file not readable: images/debian.png
doc/doc/download.rst:511: WARNING: image file not readable: images/ubuntu.png
doc/doc/download.rst:513: WARNING: image file not readable: images/mint.png
doc/doc/download.rst:509: WARNING: image file not readable: images/debian.png
doc/doc/download.rst:511: WARNING: image file not readable: images/ubuntu.png
doc/doc/download.rst:513: WARNING: image file not readable: images/mint.png
doc/doc/download.rst:517: WARNING: image file not readable: images/rhel.png
doc/doc/download.rst:515: WARNING: image file not readable: images/centos.png
doc/doc/download.rst:519: WARNING: image file not readable: images/fedora.png
doc/doc/download.rst:521: WARNING: image file not readable: images/opensuse.png
doc/doc/download.rst:525: WARNING: image file not readable: images/arch.jpg
doc/doc/download.rst:525: WARNING: image file not readable: images/arch.jpg
doc/doc/download.rst:527: WARNING: image file not readable: images/gentoo-signet.png
doc/doc/download.rst:529: WARNING: image file not readable: images/git.jpg
doc/doc/download.rst:529: WARNING: image file not readable: images/git.jpg
doc/doc/download.rst:509: WARNING: image file not readable: images/debian.png
doc/doc/download.rst:511: WARNING: image file not readable: images/ubuntu.png
doc/doc/download.rst:513: WARNING: image file not readable: images/mint.png
doc/doc/download.rst:515: WARNING: image file not readable: images/centos.png
doc/doc/download.rst:517: WARNING: image file not readable: images/rhel.png
doc/doc/download.rst:519: WARNING: image file not readable: images/fedora.png
doc/doc/download.rst:521: WARNING: image file not readable: images/opensuse.png
doc/doc/download.rst:523: WARNING: image file not readable: images/windows.jpg
doc/doc/download.rst:525: WARNING: image file not readable: images/arch.jpg
doc/doc/download.rst:527: WARNING: image file not readable: images/gentoo-signet.png
doc/doc/download.rst:529: WARNING: image file not readable: images/git.jpg
doc/pages/support.rst:: WARNING: image file not readable: images/gitter-badge.svg
```

**Comment by xinetzone** [comment]
If you remove the `sphinx-build` from `invoke run -t build-site` (Corresponding to the ` update.py` ) and use `invoke doc` instead, the logic might be clearer.

**Comment by xinetzone** [comment]
`invoke run -t build-site` (Corresponding to the ` update.py` ).
If you remove the sphinx-build from SS and use 'Invoke Doc' instead, the logic might be clearer.

If you remove the sphinx-build function and use 'Invoke Doc' instead, the logic might be clearer.

**Comment by kayhayen** [comment]
@xinetzone that's fine not everybody likes these things, I mean telcos. Seems you did a fair bit of work there, I was offline for a bit, and will check it out now. The calls seem to make sense.

**Comment by kayhayen** [comment]
I think I am starting to understand how something like `doc.clean` is solved, very nice. 

One thing I am seeing is this:

```
# Usage doc/API site (published as e.g. docs.myproject.org)
intl = _site("intl", "the API docs subsite.")
doc = _site("doc", "the API docs subsite.")
```

I believe the "API docs" should indeed be actually different site. Right now, conf.py insists on `develop` checkout, solely such that a rather expensive (run time wise) module can find the Nuitka develop code, but actually I think we should get rid of that for the normal build. Updating downloads, manuals, etc. yes, but for normal development of pages, that's great to not have to do any checkout whatsoever. This is also not for now, but it seems you have made it real easy here, to just actually do it like that, and have say e.g. "api" through another call of `site`. But I believe the current name might be inaccurate.

I would switch the default for run to `--build-site` and probably include post-processing there unless disabled. I do have it separate because sometimes I develop the post-processing. I can make that change later, no problem. The post-processing is very critical for page load times, esp. on mobile devices. Also doesn't take long.

Side topic, not important right now: Does invoke have some form of memory? I recall encountering `doit` and it had a database for tasks and their dependencies, because running `run` manually sucks, but nobody has to do that, really outside of maybe me occasionally. It would be nice to e.g. define "virtualenv" as a dependency, but to keep track of it if it was run already.

**Comment by kayhayen** [comment]
So, this is actually looking very good to me now, good job @xinetzone and I seem to get it. I think the `.gitignore` in `intl` is what keeps `posts` from being there. Not sure if that list should be expanded with my recent additions to the readme. But I guess, this looks like something that I can now compare if it works the same.

One question I have, is there a URL for the gh-pages generated? I think it would be nice for translators to see the effect immediately after push. I would put a disabling robots.txt for search machines there, and have it otherwise on nuitka.net when I trigger the CI of mine. That seems like a good way to go.

**Comment by kayhayen** [comment]
I believe, using `invoke` to install the virtualenv is causing a chicken and egg problem, and probably not a good idea, instead invoke should know how to run commands inside of the pipenv. I think it's not actually used in your example code and could be dropped as a target. Instead all commands inside of invoke should be prefixed with "python -m pipenv run".

**Comment by xinetzone** [comment]
Regarding the name, we can discuss some better names.

About `gh-pages`, see https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site.

**Comment by xinetzone** [comment]
The `gh-pages` branch stores Github Action auto-deployed pages that can be previewed directly.

`deploy.yml`:

```yaml
    - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/
```

**Comment by kayhayen** [comment]
I added it, but it's giving an error right now.

**Comment by kayhayen** [comment]
So this works for me without a regression now: 

```
   # Creates a virtualenv with all that is needed to develop the
   # site.
   python3 -m pip install -U invoke
   python3 -m invoke virtualenv

   # Now lets build the site, to see if it's all correct.
   python3 -m invoke run -t build-site

   # Start local web server with the site, and do automatic
   # rebuilds
   python3 -m invoke run -t serve-site

   # Browse it (Linux)
   xdg-open http://localhost:8080
   # Browse it (Windows)
   explorer http://localhost:8080
```

**Comment by kayhayen** [comment]
I will make a diff now with main branch, and try to eliminate differences to zero. The progress output from invoke doesn't use colors vs. the one on main, I noticed. It is loosing the standard input / terminal somewhere, is it?

**Comment by xinetzone** [comment]
We try to do some work in Python instead of commands like `mv` in Linux. In this way, we can avoid our work being dependent on the operating system.

**Comment by xinetzone** [comment]
`invoke` supports tty, which I have not studied. For details, please refer to:   [shell-tab-completion](https://docs.pyinvoke.org/en/stable/invoke.html#shell-tab-completion).

**Comment by kayhayen** [comment]
I am adding `sphinx_book_theme` to the pipenv, not sure why things worked before, probably because I now insist better on running inside the pipenv only.

**Comment by kayhayen** [comment]
But I was wondering, if this had anything to do with RTD theme being bad for Chinese, or is this just a preference of yours?

**Comment by xinetzone** [comment]
It's just my preference.

**Comment by kayhayen** [comment]
And another observation, I made, is this: You are using `"target": f"{name}/../output/html"` in the `site`, so that is actually always `output/html` and it's done after in `output` there is already the result of `update.py --build-site`, which looks kind of wrong. I am not sure, what that does. So the actual `intl` output is not yet under `output/zh_CN` or where we think it should go.

**Comment by xinetzone** [comment]
`intl` in `build()` is redundant, should: 
```python
def build(c,
          opts=None,
          language=None,
          source=None,
          target=None,
          nitpick=False):
```

**Comment by kayhayen** [comment]
I remove it, but the paths seem inconsistent, and I think the conf.py needs a bit of merging with the other one. Mid term we will have to use a common part for these.

**Comment by xinetzone** [comment]
```python
if language:
        opts = f'-D language={language}'
        target = f'{target}/{language}'
````

Use `invoke intl -l zh_CN` instead of `invoke intl`.

**Comment by kayhayen** [comment]
yes, surely `de` is coming soon

**Comment by xinetzone** [comment]
`invoke doc` and `update.py --build-site` functions overlap.

**Comment by xinetzone** [comment]
Consider handing over all the work of building HTML using `sphinx-build` in `update.py --build-site` to `invoke doc`.

**Comment by xinetzone** [comment]
`update.py --build-site` is only responsible for updating the document (`.rst`).

**Comment by kayhayen** [comment]
I just fixed up logo path, I first want it to build again, before modying more.

**Comment by kayhayen** [comment]
Actually, that is `--update-docs`, I think `--build-site` was changed on `main` to not do anything to the documents anymore, so I will be able to drop it and replace it with `invoke doc`.

**Comment by kayhayen** [comment]
Ok, green again, I think I broke API docs in the intl subsite, but it didn't really care. I am now pushing the removal of update.py usage for building and adapted the paths, lets see how that goes.

**Comment by xinetzone** [comment]
I have an idea: separate 'doc/' into 'old' and 'docs/' documents that may change, and store them in 'old' and 'docs/' respectively. Then merge 'intl/' into 'docs/'.

**Comment by kayhayen** [comment]
For now I got it to somewhat work:

https://nuitka.github.io/Nuitka-website/intl/zh_CN/index.html

**Comment by kayhayen** [comment]
But there is plenty of issues, the images like you said, and the duplication of `conf.py` of which you are also not really sure anymore, right?

**Comment by xinetzone** [comment]
Generate 'old/' as a separate 'docs/' subdomain.

**Comment by xinetzone** [comment]
Using `invoke docs` instead of using `invoke doc` and `invoke intl` separately can avoid image link problems.

**Comment by xinetzone** [comment]
`old/` refers to old blog posts like `posts/` , `pages/`.

**Comment by xinetzone** [comment]
The localized operation is done by something like `index doc -l zh_CN`.

**Comment by kayhayen** [comment]
So my game plan now, is to make sure, I can use this branch for my internal CI that deploys, and to have some kind of sharing between the two `conf.py`, such that they do not repeat themselves. But for now I need to turn to other things. I will continue work on this later.

**Comment by kayhayen** [comment]
Ok. One thing I saw from the diff is this:

```
-#: ../../Nuitka-develop/Developer_Manual.rst:8
+#: ../../Nuitka-main/Developer_Manual.rst:898
```

These files are now copied into the repo, as produced by `--update-docs` and should not be taken from the checkouts at all after that. That step is also kind of optional now. Users do not have to execute it except for importing the changes, but CI will do that, so changes in the repo take immediate effect.

In fact, right now, `update.py` is using `Nuitka-factory` so it can format code, check code, etc. some tools, but no file content from it is used. And `Nuitka-develop` is needed only for the API docs, which should be built against that branch. Like I said before, that probably means it could be separate.

**Comment by kayhayen** [comment]
I am rebasing it on `main` where some changes were are coming from, for clearer sight.

**Comment by kayhayen** [comment]
I will also make it stop using `Nuitka-factory` now, the code in `Nuitka-develop` will be good enough, and in `conf.py` it will use the code from `update` above, so it's not duplicating effort there. With that `invoke doc` works directly for me. I think before my instructions in the `README.rst` were not working.

**Comment by kayhayen** [comment]
The workflow still doesn `invoke intl -l zh_CN`, but I am assuming, that is to be removed, right?

**Comment by kayhayen** [comment]
So, when you build `doc` with `-l zh_CN` it takes too many pages, all of `posts` and some more, that is probably why you want the split, right?

Lets think this through first. Wouldn't it make more sense to get `intl -l zh_CN` to work without errors. From what I am seeing, every including statement, be it image, or otherwise, will be wrong for this. That is kind of ugly indeed, but maybe we can manage with (automatic) duplication of git ignored stuff. It feels like something that can be done easily too.

With the `extra` split, I am worried that the integrity of the sphinx build will suffer, because not the whole thing will be visible to Sphinx causing issues. So currently I am kind of against it.

**Comment by kayhayen** [comment]
Ok, found a few more things, templates were not shared, which is why the post processing fails to work on actions, now it ought to work.

**Comment by kayhayen** [comment]
One thing, that is regressing kind of, is the local web server, that I had with Sphinx. It was kind of broken by post processing not being done for rebuilds. Would you know of a simple command that will just serve a folder and watch for changes, even without the incremental rebuilds?

**Comment by kayhayen** [comment]
Where should the copying of the image files needed happen, inside the `intl` target looks ugly. I think I will first get rid of `pages/images` on main branch, where there is only one image and then just git copy the images.

For the main site, things look ready for use. Of course, we need to think about how to indicate language switching being possible as well, what's your ideas for that? I was thinking some flags dropdown in Javascript must be available somewhere, although I would love to use CSS only solution. Any pointer to a place that uses Sphinx and does that well?

**Comment by kayhayen** [comment]
I think, the post processing could clean up the absolute paths for images. I copied the images, they are already flat in `intl` which is good, and it seemed to work.

Since this is not causing any regression for me anymore, outside of the lack of local web server, I will put it on the main branch, so we can close it here, and open issues for the things that are remaining.

**Comment by kayhayen** [comment]
I am merging this, despite Github pages looking awful. No CSS, no JavaScript, no image links are working there, but they ought to work on nuitka.net so lets see how it does there. I need to be very careful to not deploy accidentally a delisting from Google and friends, so please allow me to take some time for that.

**Pull request merged**
