### PR TITLE
Fix typos in README and documentation comments

### PR DESCRIPTION
**Pull request by ubmarco**
This PR corrects several typos found in the README file and documentation comments within the code. These corrections improve the readability and professionalism of our project's documentation. No changes were made to the actual code logic, ensuring that this PR solely enhances documentation quality.

### CODE REVIEW

**Comment by ubmarco** [comment]
Smart bot :)

**Review by kayhayen — APPROVED** [review]
Thank you so much for spotting there.

**Comment by kayhayen** [comment]
> Smart bot :)

Indeed, although sometimes it gives advice I disagree with, generally it's very good at things and so good. Let me also take the time to thank for you for the PR and report.

**Comment by kayhayen** [comment]
Just curious, did you use the new devcontainer to make this, or just straight git?

**Comment by ubmarco** [comment]
Honestly, I created the PR completely on the website while reading the docs. Not even an IDE open :)
But good to know there's a devcontainer setup.

**Comment by kayhayen** [comment]
Just curious, it's supposed to be dead simple now, provided you use Visual Code. We are preparing a proper manual for it, but typos work that way of course too. Thanks again.

**Pull request merged**
