### PR TITLE
Automated Deployment Chinese Version

### PR DESCRIPTION
**Pull request by xinetzone**
Automated Deployment Chinese Version Previews are available at https://daobook.github.io/nuitka-doc

### CODE REVIEW

**Comment by kayhayen** [comment]
I like the idea a lot. I am a bit uncomfortable with hosting content that I do not understand. I need to find a solution.

**Comment by xinetzone** [comment]
Here is my solution: https://daobook.github.io/nuitka-zh/use.html

Bilingual support, the home page is in English (https://daobook.github.io/nuitka-zh/) and the subpage https://daobook.github.io/nuitka-zh/zh_CN is in Chinese.

**Comment by xinetzone** [comment]
This can be done with the command:

```sh
sphinx-intl update -p . /output/gettext -l zh_CN,en,de
```

Provide more language support.

Translators just focus on translating ``locales/` for the corresponding language, and finally use ``git push`` to automate the deployment.

**Comment by kayhayen** [comment]
This is indeed impressive. I think a button series to switch languages would be prudent to have, probably with flags or something like many sites do.

Also can you remove the "post" section from translation, it is inflating it by a lot, and historic information mostly, and I think there are other documents, which might make less sense. Also some sections of the manual make no sense, e.g. in credits, and these things. What is your take on this?

**Comment by xinetzone** [comment]
Separate English original from other languages

**Comment by xinetzone** [comment]
new solution: https://daobook.github.io/nuitka-doc/use.html

**Comment by Fire-Cube** [comment]
I'm here

**Comment by kayhayen** [comment]
Hello @xinetzone and @Fire-Cube you are both apparently interested in helping with translations of the Nuitka website. I have thought about this, and I think we should indeed put `sphinx-intl` to use. I think a rebase of this branch and a partial merge are definitely worth having. Since nuitka.net is now on a CDN, my main goal would be to have `de.nuitka.net` and `cn.nuitka.net` subdomains that you more or less control.

One concern is falling out of data for translations, which is why we need to make sure to restrict this to an acceptable subset and have a language switcher available.

I would give you direct commit rights on Nuitka-website to maintain these translations. However, I would want you to sign as responsible for the content. You would form the core of a translation team.

For the Nuitka command line app, there will be links with nuitka.net, short links, that will offer also translation. With every kind of output, we should associate a URL. People can click in terminals for web links easily these days.

Does this sound an acceptable plan? If so, we need to start by rebasing this branch and drilling down the amount of translatable pages. I can do the hosting side. We can keep Github pages, if that makes it easier for you to develop, but I would like to get rid of it eventually for sure.

Yours,
Kay

**Comment by xinetzone** [comment]
> 

I agree with this approach.

**Comment by Fire-Cube** [comment]
I like that too.  For Nuitka reports I could create a page with all reports and link to them with anchors.

**Comment by kayhayen** [comment]
I have created a Team and sent you the invites. That teams get push access to the central repo. Next up, I will look at your branch @xinetzone but do you have a chance to attempt to rebase it yourself? I think I moved stuff around, probably I can do this best, but then I don't know what it is.

We should move your branch to a central one, I suggest `translation` for now. Then from there, I can try and reduce the delta, such that the `main` branch carries it.

I will also set up the discussed subdomains of `https://nuitka.net` such that it will be deployable to there. I think I want to have a workflow there, where translation building is a separate step though. Then we can try and work on the joined branch. For a security measure, my CI will build only from my private clone of the repo, also to avoid breakage.

**Comment by xinetzone** [comment]
@kayhayen [invoke](https://github.com/pyinvoke/invoke) can help us better organize tasks.

**Comment by xinetzone** [comment]
Invoke supports multi-tasking deployments that integrate internationalization and legacy projects into a unified interface.

**Comment by xinetzone** [comment]
Set up the discussed subdomains of https://nuitka.net is good idea. Setting `translation` branch also agrees. The current focus is on narrowing the differences between `main` and `translation`.

**Comment by kayhayen** [comment]
Great, no conflicts. And invoke is fine. I will make a stab at narrowing down differences tomorrow. Please forgive me if commit history will suffer somewhat though.

**Comment by kayhayen** [comment]
I will migrate your branch to the central repository right now. I am getting second thoughts on the subdomain, it may just make things more complicated and can be done later too. Let me know if I am missing a push, or simply rebase it. I will try my best to make an attempt to merge things into `main` that have no adverse effect immediately. Thanks for working with me here, feels good.

**Comment by kayhayen** [comment]
I rebased to `main` with only unrelated changes from past days, and pushed it as `translation`. In my mind, this is a feature branch, that we want to get rid of.

**Comment by kayhayen** [comment]
I like using the `include` directive rather than using symlinks in the file system, makes it a lot more clear.

**Comment by kayhayen** [comment]
What is your opinion on the checkouts. Right now, Nuitka is getting a work tree of Nuitka such that it has the tools of Nuitka available, that is fine. We might also just install it as a requirement, though. 

That will make life simpler. And then we can include copies of the logo, etc. as plain files and have a more explicit update. In some cases, I want main, sometimes, I want to develop there. But a current state could always be in the repo. In this way, it would be workable without any updating steps, and the CI would update downloads and update changelog and update docs, but you don't have to do it locally anymore. The logo file is not going to change, really. And should somebody provide a PR for say the user manual of Nuitka through Nuitka-website, I can still copy it over to where it is used from.

**Comment by kayhayen** [comment]
As an aside, I would really want to continue to use `pipenv`. It's very important, because versions of tools must be fixed, simply because we do a lot of post-processing that relies on things to be upgraded with care. The theme changes and the replacements in the HTML are all delicate, but needed for the Website to have acceptable speed. Actually, Sphinx is by default pretty crappy for performance, despite being a static page set.

**Comment by kayhayen** [comment]
Just use `python -m pipenv shell` if it annoys you to use `python -m pipenv run`.

**Comment by kayhayen** [comment]
I also agree with just pip installing Nuitka. For API docs, I would want to use develop soon. But I guess in that case, Nuitka develop should be pip installable anyway. I am not sure how to upload RC versions to PyPi, though. If you have more skills there, let me know.

**Comment by kayhayen** [comment]
The `sphinx-intl` is not an extension it seems, https://www.sphinx-doc.org/en/master/usage/advanced/intl.html and I was kind of expecting it to be one. Need to check your build script.

**Comment by kayhayen** [comment]
Yes, I was kind of expecting this to hook with `sphinx-build . ../output/` and be good. But then I also don't really know what sphinx-build does.

**Comment by xinetzone** [comment]
see [sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html).

**Comment by kayhayen** [comment]
So, I am using a sphinx build script that is a more general frontend there, and could do more than html, but that is not needed, very fair and intl doesn't even consider using it, very well.

**Comment by kayhayen** [comment]
Symlinks are actually supported in newer Windows 10, you can make your git do it. It may not be a good idea though, since it involves extra steps. I have removed the symlinks to the checkouts and include as full copy. Added benefits, you do not have to do `--update-docs` or else you get a failure. There is more symlinks, I will fight them until they are all removed.

Also, I will try the invoke, I understand `tasks.py` but `_docs.py` has stuff that is beyond me. Probably sphinx details in there, right?

**Comment by kayhayen** [comment]
I was going to switch to having nuitka installed via pip, but the website is using the autoformat tools and generally a lot of code that is not in that pip package, so we cannot go that route. We will have to git checkout Nuitka-factory, unfortunately. I do not really want to put code in the package that will not be used by the compiler. Maybe one day these tools become their own package, but not now.

**Comment by kayhayen** [comment]
Are you two building on Windows then?

**Comment by kayhayen** [comment]
We probably should create a new PR, I will attempt to do that now.

**Pull request closed without merging**
