### PR TITLE
move documentation from nuitka.net to readthedocs for better navigation

### PR DESCRIPTION
**Pull request by gunungpw**
add config file and other requirement for moving the documentation from [nuitka.net](https://nuitka.net/) to [readthedocs.org](https://readthedocs.org/) for better navigation and automatic update.
link from main site can be redirect to new documentation in readthedocs.
for demo this page i make from fork [demo](https://docs-nuitka.readthedocs.io/en/latest/index.html)

### CODE REVIEW

**Comment by gunungpw** [comment]
if this change can be merge, maybe need more formatting in `.rst` file to delete `.. content` line because readthedocs already have ToC build-in

**Comment by kayhayen** [comment]
I absolutely love this, it's indeed very nice. My only complain is that you misspelled my name, but I am going to merge it anyway. Do I have to setup an account with them to make this work now?

**Comment by gunungpw** [comment]
> IDo I have to setup an account with them to make this work now?

yes, just follow official [docs](https://docs.readthedocs.io/en/stable/tutorial/#)

**Comment by kayhayen** [comment]
Thanks, I think I will need to setup the account now, thanks for the good job, this is precisely the kind of help I need.

**Comment by gunungpw** [comment]
It's my pleasure.

**Comment by kayhayen** [comment]
Will you delete the demo so that it won't be confused later on?

**Comment by kayhayen** [comment]
Regarding the tocs, PyPI and Github would like to have at least the one in the user manual. I will add something that removes them for the site build.

**Comment by gunungpw** [comment]
> Will you delete the demo so that it won't be confused later on?

@kayhayen Okay, i already delete the demo

**Comment by kayhayen** [comment]
Can you check it out, and let me know if i messed something up?

Regarding TOC, change is coming, I want to remove factory from toc, and I was wondering if it wouldn*t be possible to build this locally, I like previews esp. if I consider to move more to it.

**Comment by gunungpw** [comment]
You can preview sphinx docs locally with `sphinx-autobuild` from PyPI, this the [github_repo](https://github.com/executablebooks/sphinx-autobuild). or you can use VS Code extension 
`lextudio.restructuredtext`

**Comment by gunungpw** [comment]
i like use `sphinx-autobuild` because live-reload feature. I will help check out the docs, so far the image link is broken but i'ts not important in my opinion. if you want to move more stuff to it maybe add `changelog.rst`, `download.rst` or other stuff that need to change periodically, so the website just place to announce and advertisement/publicity

**Comment by kayhayen** [comment]
Ok, I managed to remove logo and contents from the manuals, you are correct that Changelog ought to go there too.

**Comment by kayhayen** [comment]
I think I want to build it with their theme and stuff, it's available too, and then probably just the real files to deploy, not sure if and how I keep nikola then.... probably not for a lot of things.

**Comment by kayhayen** [comment]
I think I managed to build with their theme, and integrate stuff into the nikola building script for now. I will gradually move stuff over, but I think readthedocs.io will not be needed anymore then. The PDF downloads are not that important to me, we generate PDFs with rst2pdf already, and they were looking better.

**Pull request merged**
